### ISSUE TITLE
Add custom syntax support

### ISSUE THREAD

**Issue by eyelash** [xi-editor/xi-editor#1068]
Similar to #637 but for syntaxes instead of themes.

I also noticed that syntax highlighting is missing for *.toml and *.xiconfig files which should probably be working out of the box.

**Comment by cmyr** [comment]
Yea, I think we're about ready for this. It would also be nice to ship with our own set of default syntaxes; in particular I'd like syntaxes for git stuff (commit messages in particular) and toml is a clear omission.

If someone is interested in working on this, I'm happy to mentor; the main thing to do is go look at how syntect handles loading syntax files.

**Comment by kanishkarj** [comment]
@cmyr I would like to check this out.

**Comment by kanishkarj** [comment]
Hey, I have figured out how to load custom syntaxes using syntect. What should I do next @eyelash @cmyr ?

**Comment by cmyr** [comment]
So there are at least two things I think we'll want to do. The first one is to have our own default syntax set that we support, so that we aren't relying on whatever is bundled with syntect. The second one is to have some way that the user can add additional syntaxes that will be loaded by syntect.

The first of these is easier; I think we will want to create a new repository where we keep syntax definitions, and keep a special syntect packfile of these, which we'll include in the syntect plugin binary, and load instead of just loading the defaults.

**Comment by kanishkarj** [comment]
Shouldn't we close this issue and create a new issue : dynamic loading of syntaxes

**Comment by jansol** [comment]
Sure, go ahead.
