### ISSUE TITLE
Decouple xi-rpc from JSON

### ISSUE THREAD

**Issue by kvark** [xi-editor/xi-editor#1235]
# Xi-Editor Issue Template
- [x] I have searched existing issues and could not find my issue.
- [x] I have studied the documentation.

## Details

I'd like to use xi-rpc for inter-process communication with a different Serde implementation than JSON, for example: RON or bincode would have different trade-offs and may be more suitable.

Currently, `serde_json::Value` is showing up quite a bit in the API. If I understand correctly, the library is designed to only operate with self-describing data. This means one can't use it with `bincode` if the receiver knows exactly what type it expects?

**Comment by cmyr** [comment]
Pardon the slow response, as is probably evident, this isn't anyone's focus at the moment.

To try and answer the question: for some annoying reasons, we do some introspection of the received json early on, in order to determine if it's a response to an earlier message; if it is then it needs to be handled immediately, since it's possible that our main thread is blocked waiting for this message.

If you're still thinking about this, my honest suggestion would be that you start a new crate, copy xi-rpc wherever you like, and then try and get it working with the serialization of your choice.

**Comment by kvark** [comment]
We decid to go with Mozilla's standard IPC, so this is not an issue any more for us. Please feel free to close!

**Comment by cmyr** [comment]
glad you've figured something out. :)
