### ISSUE TITLE
Is it possible to avoide Camel case to snake case in rpc.rs

### ISSUE THREAD

**Issue by sucrecacao** [xi-editor/xi-editor#1306]
# Xi-Editor Issue Template
- [X] I have searched existing issues and could not find my issue.
- [X] I have studied the documentation.

Hello,

I'm new to xi-editor and wanted to hack it a bit. My first initiative was to search for rpc requests in the source code and trace the code from there. But due to the camel to snake case translation in `rpc.rs`, I didn't find any result when search for `move_right` for example.  At that time I didn't thought to look into rpc.rs, even if it seems obvious for me now. 

I had to explore the code quite a while and it by mistake that I realize that the rpc request were written in camel case in the source code. ( and then I could read the code like a book :) )

 I think it would be nice to unify the syntax, so its easier for new comers. If I had trouble it's likely that other people will encounter the same problem.

Is this translation necessary?

**Comment by Cogitri** [comment]
Using `CamelCase` for enum variants is the default for Rust, see https://doc.rust-lang.org/1.0.0/style/style/naming/README.html. As such, we probably don't want to change this, sorry about that. I suppose we *could*  put a comment there, but I doubt that would actually make it easier to find. I suppose it'd be better to make a "New Comers" guide or something since the Xi codebase can be rather confusing at times (but the time might be better spent improving the API docs).
