### ISSUE TITLE
Include line numbers when sending updates from core

### ISSUE THREAD

**Issue by cmyr** [xi-editor/xi-editor#184]
Since line wrapping happens in the core, the client needs to be informed whether a line is a real/logical line or part of a wrapped line.

The easiest place to put this is probably in the line structure, which already includes cursor positions and selection information. The most trivial solution might be to just send the logical line number with each line, and the client can decide how to render line numbers. Alternatively, the client could do more of the work, and there could be some optional field on each line, "newline", which if presents instructs the client to increment an internal counter. 

I err towards being more explicit, but I'm not sure how valuable minor optimizations are, here. If they're valuable then a slightly more complicated protocol may be worth slightly more complexity.

**Comment by raphlinus** [comment]
I think the answer is to include line number as effectively an Option<usize> with every line. This presents no problem when rendering new lines. Currently, deciding what to re-render is crude, so that _all_ lines get rendered.

However, I really want to get minimal update (see #152). In that case, when you (say) insert a line, then the line numbers of all lines following that increment by one. I don't want to explicitly send the line numbers for all the lines that otherwise do not change.

I think I've worked out the answer (after struggling with more complex ideas involving maintaining a delta). Essentially, the "copy" operation is augmented to contain an initial line number (technically, the count of present line numbers for all lines preceding), call it `ln`. When copying a line, if a line number is present, then `ln` is incremented, and the line number is replaced with `ln`.

The "update" op could be extended to allow flipping the present state for a line number, but I'm more inclined not to do that, and just require the core to do a "skip" + "ins" with the new line state.

Note also that the update protocol needs to send a maximum line number, for calculation of the gutter width.

**Comment by raphlinus** [comment]
Ok, thinking about it some more, the proposal above _almost_ works, but doesn't handle the case where valid lines in the line cache may be non-contiguous, i.e. there are valid lines, invalid lines, then more valid lines.

That said, what I think will work is sending a delta with each "copy" and "update" operation. In the current implementation, these deltas will always be 0 (because it blows away existing lines and re-renders everything), so as a consequence it would be possible to get a first cut implemented quickly (calculating the line number deltas will simply be an additional responsibility for minimal update when that happens).
