### ISSUE TITLE
multi selection polish

### ISSUE THREAD

**Issue by cmyr** [xi-editor/xi-editor#323]
pulling out some todos from #188.

- [x] Copy-paste of multiple lines into an equal number of cursors should paste one line per cursor. Current behavior is to paste all lines (separated by newline) into all cursors

- [x] Transpose (^T) should rotate the contents of selection (non-caret) regions. Currently they're ignored.

- [ ] Selection region merging, when one region is forward and the other backward, always resolves the direction of the merged region to forward. I think better behavior would be to match the other parameter (ie the region added later).

- [x] Update of style spans on edit is based on edit summary rather than fine grained edit, so everything from the beginning of the first region to the end of the last loses style. This is recoverable because (according to the current plugin protocol) the plugin will re-highlight all of that, but it's not ideal.

**Comment by sp3d** [comment]
The first of these is really interesting; naïvely I'd expect multi-cursor pasting to broadcast a single copied string to all cursors rather than splitting on newlines, and would only expect different pastes per cursor if the text had been copied from a set of multi-cursor selections. In either case, what happens when the number of objects to paste isn't the same as the number of cursors?

Are both kinds of functionality (broadcast and pointwise paste) accessible in other editors?

**Comment by trishume** [comment]
@sp3d AFAIK in all common editors with multi-select (Sublime, Atom, VSCode) the way it works is that it broadcasts the copy buffer to all cursors unless the number of cursors is equal to the number of lines, in which case it pastes each line's contents at the corresponding cursor.

The reason is so that when you copy using multiple cursors, it gets put into the clipboard as multiple lines, and then if you move those cursors somewhere else and paste it properly acts like each cursor has its own paste buffer, but without having to make the clipboard actually be a fancy data structure.

I think this is a feature rather than just laziness about making the paste buffer fancy. First of all, I actually use this, I've copied a bunch of lines using a single cursor and then column-selected to paste each line in a different place. It's also not nice to have hidden state in the paste buffer that you can't observe just by pasting, two buffers that paste to the same thing in the single-cursor case should act the same in a multi-cursor case.

**Comment by sp3d** [comment]
Thanks for the info about other editors.

I agree it's handy to be able to paste in a way that splits an N-line selection (or M*N? how do our peers handle copy/paste of multiple multi-line selections?) across N cursors. But I would advocate storing an additional clipboard format that doesn't discard knowledge of how many selections text came from when we copy, and having a way to access paste functionality that explicitly broadcasts or splits.

**Comment by trishume** [comment]
I acknowledge that model is conceptually cleaner, but it is also substantially more complex to implement, involves learning more operations, and involves hidden state that violates the normal model of what the clipboard is. I prefer the simplicity of "broadcast unless exact match then split" because I don't think the extra cases handled more the complex model are very useful.

I use multi-cursors a lot and have never encountered the case of wanting to paste multiple lines at multiple cursors. I don't know if I've ever even copied multiple lines per cursor.

I also think the fact that every other multi-cursor editor implements copy-paste this way makes this a good way of implementing it if only for compatibility with how people expect multiple cursors to work.

But really I do agree with you that the model is nicer, it's just these other concerns make it not an effective use of implementation effort. If you were to implement it though in a way that works nicely across platforms and interoperating with the native clipboard (I think this would involve adding a custom multi-cursor mime type to the pasteboard along with the plain text and using that if it is present on paste), I don't think I personally would say no, I can't speak for others though. We did discuss this on IRC a while ago and the consensus seemed to be in favor of the normal behavior of other editors.

**Comment by cmyr** [comment]
@sp3d: I’m kind of on your side, in that I do think that some slightly fancier data structure is more elegant and more ‘true’; but I’m also very happy to put that work on some “possible avenue for future investigation”, because I’m really hard-pressed to come up with an actual use-case, and I don’t think it really justifies the development time. But: on IRC I was basically making the argument you’re making now.

**Comment by shtanton** [comment]
There hasn't been much activity here in a while, but it's so nearly finished!

If the last point seems like a plausible first contribution to the project then I can get started.
