### ISSUE TITLE
Auto-indentation

### ISSUE THREAD

**Issue by cmyr** [xi-editor/xi-editor#424]
Auto-indentation is one of the major missing features in xi right now. What is our approach?

1. Is providing indentation a plugin's responsibility? (Seems like it.)
1. If providing indentation is a plugin's responsibility, what does the API for that look like?
2. If providing indentation is a plugin's responsibility, how do we approach the syntect plugin? Do we add support upstream (is @trishume open to this?) or do we add support locally?

**Comment by raphlinus** [comment]
1. Yes absolutely.

2. The existing API for plugin-originated edits is designed for exactly this use case. I do expect some refinement around things like making sure the inserted indentation is in the same undo group as the user-inserted newline.

3. In the end state, I would like to see support in syntect, because [increaseIndentPattern](https://manual.macromates.com/en/appendix#increase_pattern) and friends are part of TextMate syntax definitions and I believe respected by all modern editors. As a short term expedient, I can see adding simpler logic by hand to the syntect plugin before support lands in syntect proper.

A continuation of this work is "electric parentheses" but I think getting solid auto-indent only should be the immediate priority.

**Comment by purpleP** [comment]
I'm not a contributor, but as I've already said being dissatisfied with every editor I tried I've spent some time thinking about architecture of extensible, rpc-based editor like yours. One of the things I have come is that correct indentation and autoclosing parentheses, xml-tags and stuff like that is impossible to do right without full-fledged parser. As a community we should either demand language authors to provide fail-safe lazy parsers (so they wouldn't have to parse whole document, but only relevant part of it) or create infrastructure to do this. Maybe we could start discussion about making this part of language servers.

**Comment by dlee** [comment]
In line with what @purpleP stated, this new incremental parsing library looks promising: https://github.com/tree-sitter/tree-sitter/.

**Comment by Kwarrtz** [comment]
What's the status of this now? I've heard that auto-indentation is close to landing. If so, which approach has been adopted?

**Comment by cmyr** [comment]
I'll be writing more about this in the coming weeks. I have a mostly working implementation that's based on syntect metadata, but this has raised bigger questions about language support more generally, that I think requires some more bottom-up thinking.
