### ISSUE TITLE
Semantic information and the update protocol

### ISSUE THREAD

**Issue by cmyr** [xi-editor/xi-editor#643]
## Semantic content and the update protocol

This is followup from a preliminary discussion today about @scholtzan's GSoC project (#634), although it is relavent to a bunch of upcoming work.

These are two general questions that I was left with after that discussion; @raphlinus  and @scholtzan  may have other questions in mind.

### Question 1: Should selection/find highlight be considered a 'style'?

We use the style system to indicate things like text color and decoration. Currently, we also use two reserved styles to indicate selection regions and regions highlighted by an active search.

While text style can be thought of as a property of the document text itself, selections and highlights are transient properties of the editor. By overloading the styles system for these two purposes, we are making decisions about the presentation of information that may best be left up to the client; for instance a client may choose to show a find result as an outline rather than as a background color.

Additionally, background color is an attribute that can be changed by the style system. (theoretically; this is not currently enabled). By overloading the style system to show selections, we would currently be replacing any style-specified background colour, where we might prefer to show a selection drawn with some transparency overtop of a style-specified background color.

### Question 2: How will the addition of new types of metadata influence the update protocol?

How will new types of annotations and semantic information be incorporated into the update protocol?

We expect in the near future to be adding support for auto-completion, including inline suggestions. What changes to the update protocol will this require? Will all of these features operate through the update protocol, or will they work through new protocol methods?

**Comment by cmyr** [comment]
@scholtzan If you think it fits here well then that's fine, but if you think it makes more sense as a stand-alone issue that's good too! So, uh, sorry, no help. 😎

**Comment by scholtzan** [comment]
As has been discussed before (https://github.com/xi-editor/xi-editor/issues/650, https://github.com/xi-editor/xi-editor/issues/643), it would instead be better to resolve all styles in the core. For this, the `update` protocol needs to be changed. Additionally, styles need to support focused and non-focused states, since, for example, selections are styled differently depending on whether the current window is focused or not.

`update` could be changed to the following:

```
update
  rev?: number
  ops: Op[]
  view-id: string
  pristine: bool

interface Op {
  op: "copy" | "skip" | "invalidate" | "update" | "ins"
  n: number  // number of lines affected
  lines?: Line[]  // only present when op is "update" or "ins"
  selections?: Selection[]
  find_matches?: FindMatch[]
}

interface Line { 
  text?: string  // present when op is "update"
  cursor?: number[]  // utf-8 code point offsets, in increasing order
  styles?: number[]  // length is a multiple of 3, see below
}

interface FindMatch {
  start_line: number
  end_line: number
  start_col: number
  end_col: number
  query: number
}

interface Selection {
  start_line: number
  end_line: number
  start_col: number
  end_col: number
}
```

It might be desirable to have exact locations for find matches, to allow alternative representations on the front-end side. However, this would also mean that front-ends have to figure out how to map find highlights on the rendered lines.

Additionally, we would need to extend `def_style` to have the additional fields `bg_color_inactive` and `fg_color_inactive`. Perhaps for consistency `fg_color` and `bg_color` could be renamed to `fg_color_active` and `bg_color_active`.
It has also been discussed previously to do the inactive/active handling in the core. For this, the core would need to track the current view state. I would be open to either one of these approaches.

These would all be breaking changes. It would probably make sense to try to support the old `update` protocol for a while until front-ends had enough time to switch to the new protocol.

I am not 100% sure about all this, but I think it will at least get the discussion going. I would appreciate thoughts and opinions about the proposed changes.

**Comment by scholtzan** [comment]
Based on the discussions on IRC, to improve efficiency the protocol can be changed to the following:

```
update
  rev?: number
  ops: Op[]
  view-id: string
  pristine: bool

interface Op {
  op: "copy" | "skip" | "invalidate" | "update" | "ins"
  n: number  // number of lines affected
  lines?: Line[]  // only present when op is "update" or "ins"
  selections?: Selection[]
  find_matches?: FindMatch[]
}

interface Line {
  text?: string  // present when op is "update"
  cursor?: number[]  // utf-8 code point offsets, in increasing order
  styles?: number[]  // length is a multiple of 3, see below
}

interface FindMatch {
  position: [number, number, number, number]    // start line, start column, end line, end column
  query: number
}

interface Selection {
  position: [number, number, number, number]    // start line, start column, end line, end column
}
```

The client would handle the active/inactive selection rendering so that `def_style` does not need to be changed.

I have also thought a bit about how we should handle invalidation but do not have a final answer to that yet. It would probably make sense to avoid sending all selections and find results for every `update` since they often might be unchanged or there might just be small changes. Instead, only the ones that are actually changed or new will be sent, which should be similar to what we are currently doing with line rendering (except selections/find results that are outside the current view should also be sent to the frontend). Selections and find highlights will then also influence the invalidation of text lines.

There will probably be no big difference between handling selection and find highlights or even other types of metadata that might be added in the future. Sll/most of these types are quite similar in that they operate on a certain Span and have some additional information.

**Comment by portstrom** [comment]
> By overloading the styles system for these two purposes, we are making decisions about the presentation of information that may best be left up to the client; for instance a client may choose to show a find result as an outline rather than as a background color.

Then simply change the styles to be purely semantic and not include any presentational attributes. That way the frontend can manage anything it needs to manage.

From my personal notes implementing a frontend to Xi:

> Somehow someone seems to have thought that having functionality for color themes in the text editing core is a good idea. How that happened would be an interesting story to hear. Xi loads themes as binary files from Sublime. The Xi core loads color themes. The Syntect plugin loads highlight themes. How that distinction works and why it was made could also be an interesting story.
>
> I can't explain the motivation for doing things that way, but after spending some time trying to use the color theme features in Xi to change to something better than the crappy default `InspiredGithub` theme and then finding out that all of the other themes are just as crappy, it's easy to motivate why things shouldn't be done the way they have been done. When I say crappy, I don't mean it as in “They didn't pick my favorite colors”, but as in a jaw-dropping “How could anyone even use this”. There is for example not a single theme with black text or anything near black.
>
>  * The Sublime binary files are a black box to me. Maybe if you're a Sublime fanatic you can go through the penance to open the black box. For someone else it's impossible to create a new theme if you are as astonished as I am that all available themes are so crappy.
>
>  * The themes contain colors for the UI elements in Sublime. Another editor is going to have other UI elements, and the theme isn't able to provide colors for those.
>
>  * An editor may provide functionality for editing different kinds of documents, with Xi as the backend for plain text documents other software as backends for other kinds of documents. Having the color theme functionality built into the subsystem that handles plain text documents is no good.
>
> * An editor may provide a UI for editing themes. Emacs does this. The themes then can't be a read-only black box.
>
> I would rather like if Xi didn't do color themes at all, but instead sent a class name describing each span. The frontend can then do its own theming, applying the theme to the spans. As a dirty workaround, I decided to choose any theme thas has a distinct color for each kind of span I require to have a distinct color, no matter how crappy the colors are, and then not treat the colors as colors, but instead treat them as magic numbers and choose my own color for each magic number. The `InspiredGithub` theme doesn't work because it doesn't have a distinct color for field names. The “solarized” themes instead display some keywords in the same color as identifiers. The “base64” themes however work quite well. The colors I'm applying myself I take directly from Emacs.

**Comment by scholtzan** [comment]
Brain dump of how I think annotations could be implemented:

I guess it makes sense to represent annotations as `Spans<Annotation>`. To differentiate between different annotation types, we would have different annotation `struct`, for example `SelectionAnnotation` and `HighlightAnnotation`, that implement the `Annotation` trait. These annotation types have fields which represent the type-related metadata (eg, for find highlights `query_id`). These annotations would be part of `View`.

If deltas are applied to the text, then the annotation spans could be updated in a similar way like style spans are currently updated. Doing this would avoid recalculating all the annotations from scratch for every edit. If selections/highlights are changed, we will probably need to recalculate the corresponding annotations in most cases.
