### ISSUE TITLE
Missing Search Highlights

### ISSUE THREAD

**Issue by scholtzan** [xi-editor/xi-editor#650]
I wrote a simplified WIP version (https://github.com/google/xi-editor/pull/649) of find that, for now, searches the entire text and all search occurrences (it is not much different from the old find functionality). However, only the first one is highlighted (tested in xi-mac). I tried to find out the reason for this and narrowed it down to `send_update_for_plan`. It seems that only the line with the current cursor is rendered/updated, after xi receives a `Find` event and performs the search. I suspect it has something to do with the line cache shadow of the view. 

I am currently trying to find out how rendering in `View` and the line cache shadow should behave during find. Or if this should all be done in a completely different way. Any thoughts on this are appreciated!

https://github.com/google/xi-editor/issues/634

**Comment by scholtzan** [comment]
This might be a problem on the xi mac side. I forced a full re-rendering after `find` using `set_dirty` in `View`. Only the first search occurrence is highlighted. However, if I change the style for search highlights to 0 (= style for selections) in `render_styles` then _all_ search occurrences are correctly selected in xi mac. So my guess is that it is a xi mac bug.

**Comment by raphlinus** [comment]
Right, xi-mac is currently not rendering style id=1 (reserved for search highlights) at all. This would be fairly straightforward to fix, but the main reason it hasn't been is that there is a design decision to be made about where in the pipeline "special" styles get resolved into their actual appearance. For styles from plugins (syntax highlighting) this is done in the core, but not so for the two reserved styles.

The main reason style=0 (selection) is handled specially is that the appearance is different depending on whether the window is focused. I'll outline 3 possible approaches, which basically represent different places in the pipeline where resolving occurs.

1. (basically status quo). We continue to have reserved styles, and logic in the front-end to render them. Re-implement logic in xi-mac to render style 1 correctly.

2. We continue to have style 0 be reserved because of its special focus behavior, but selection highlights (and any other future spans that represent core behavior) are resolved in the core to their actual appearance, and set as a non-reserved style. There's still xi-mac work, I think the `bg` attribute is not respected.

3. We resolve _all_ styles in the core. The special focus behavior of style 0 is handled by extending def_style so that can specify two different background colors, for focused and non-focused state.

Each of these has advantages and disadvantages. I think the main advantage of (3) is that it's less special-case work by the front-ends. On the other hand, it's less flexibility in case we want the front-end to use the semantic knowledge about the meaning of the span to produce special appearance or behavior.

So let's use this issue to discuss it. If no clear consensus emerges, let's go with (1) as it's the least amount of work from the current state.

**Comment by scholtzan** [comment]
Option (1) seems to be the easiest option for now. However, I am not sure how well it is suited for supporting multiple search queries in the future. Because, if occurrences for each query are colorized/highlighted differently then the frontend would need to handle the colorization. 

With (2) or (3) it would be possible to define different styles for the different search highlights.

**Comment by cmyr** [comment]
Some points, which I'm making without a particular conclusion in mind:
	
- In many editors, find highlights (like selection highlights) are rendered differently depending on whether or not the current view is active; so find highlights should in general be treated similarly to how we treat selection highlights. So I don't think 2. works; we need to treat selections and highlights through the same mechanism, either in the core or in the client.

- There are some architectural arguments to having _all_ styles/decorations/annotations be resolved in core. Specifically, if we can come up with some shared core representation that covers styles, selections, and highlights, we can just merge them into a single set of spans, turn that into styles, and send it to the frontend. There is some nuance around deciding where cursors go (and possibly around open/closed intervals?) but if that isn't insurmountable then this could make a bunch of our code more intelligible, maybe? But it's also possible I'm being overly optimistic, our current render code already feels quite reasonable.

- our general philosophy of putting anything in core that can be shared between frontends might be worth keeping in mind. Is this one of those cases?

- If we're defining a new style for every combination of an existing style + either selection or highlight, either active or inactive, it means we're going to be defining 4x as many styles as we do currently. It's unclear that this is a problem at the moment, but might it be a problem in a future where there are a lot more styles?

- It's nice to not have special cases, and the reserved styles are definitely a special case. Having optional active/inactive styles is less of a special case; another approach to this would be to add a new `view_state` RPC that could be used to indicate whether a given view is active or inactive; it might also be used to notify core if the view's size changes (we will want some way of at least doing the size change thing, at some point anyway). This could let us avoid having distinct active/inactive styles, at the cost of an extra update being sent when active/inactive state changes, although that doesn't seem too bad.

- It isn't clear how special active/inactive styles would be implemented; would we have different fields, like `fg_active`/`fg_inactive`, or would def_style send some struct like `{"active": Style, "inactive": Style}`, or something else? Neither of these feel great, to me.

My opinion, then: I possibly prefer the approach of my second-last bullet, i.e. like @raphlinus's No. 3, except that the frontend tells core which view is active, and core handles all rendering; but I don't feel _super_ strongly. Otherwise I think 1. is the best current option.
