### ISSUE TITLE
Font colour same as background colour in some situations

### ISSUE THREAD

**Issue by ajmalsiddiqui** [xi-editor/xi-editor#752]
In certain situations, the font colour for syntax highlighting matches the background colour, thus making it hard/impossible to read it. I've faced this using the [xi-electron](https://github.com/acheronfail/xi-electron/) frontend but apparently the issue is related to the backend, as specified in [this issue](https://github.com/acheronfail/xi-electron/issues/17) in the xi-electron repo. The issue was also reproduced using the xi-mac frontend.

Here are the steps to reproduce the issue using xi-electron as the frontend:
1. build the application using the guidelines in the xi-electron README
2. Open an instance of the app using `npm start`
3. Type the following in the editor window that opens: `if ( x < 200 ) return false`

The word "return" suddenly goes invisible.

Note that just typing `return true` does not replicate the issue.

![image](https://user-images.githubusercontent.com/20279129/42893451-fc3f25c6-8ad1-11e8-909b-df0f9fd5f499.png)

**Comment by acheronfail** [comment]
Note that this happens with the `"base16-eighties.dark"` theme enabled.

**Comment by cmyr** [comment]
What syntax is being used?

**Comment by acheronfail** [comment]
@cmyr in the screenshot above I believe it’s the Python syntax.

**Comment by cmyr** [comment]
Ah okay. The problem here is that we don't draw background colors; the `return` on that line has the `invalid.illegal.name.python` scope, which that theme draws as [black text on a reddish background](https://github.com/pgaspar/base16-eighties-dark/blob/master/base16-eighties-dark.tmTheme#L541).

We will need to fix this eventually, but it depends on some changes to how we represent selections and find highlights.

**Comment by cmyr** [comment]
this is fixed in #894
