### ISSUE TITLE
Command to transpose words

### ISSUE THREAD

**Issue by portstrom** [xi-editor/xi-editor#806]
Emacs has various commands to transpose characters, words, etc. Xi has a command to transpose characters, but is missing a command to transpose words. See the [Emacs manual](https://www.gnu.org/software/emacs/manual/html_node/emacs/Transpose.html).

**Comment by cmyr** [comment]
We do have the ability to transpose selection regions. One way we _could_ think of transposing words is as a composition of the operations, 'select words' and 'transpose'.

That is: do we want to start thinking about every capability as an individual command, or do we want to create a vocabulary of command actions from which various capabilities can be composed?

To really reach the flexibility of an editor such as emacs/vim we'll probably want something like the latter. We've spoken about this previously (the idea of sending a series of commands as a single atomic command) but it's never really felt like a pressing issue.

**Comment by portstrom** [comment]
A composed command is also a command, so regardless of this implementation detail, this command will still have to be created, and how it's created doesn't matter at this point. Emacs has its flexibility because commands are written in Emacs Lisp, and you can write, compile and load new commands directly from within Emacs. Xi currently doesn't have that. Xi has taken the approach that plugins should be external processes, which I think is misguided. An external process to transpose words among hundreds of other processes for different commands is outrageous. A more suitable approach would be to have Xi run Web Assembly modules just like Emacs runs Emacs Lisp modules. Anyway, such goals shouldn't delay the implementation of the very basic transpose words feature, which can be reimplemented later should anyone decide it can be taken out of the core in the future.

**Comment by mbStavola** [comment]
I'm interested in taking this on, but more for the "composing commands" portion rather than the command itself (seems weird to have a separate command when two other commands can do exactly that already). Is that something I can work on?

I figure we could do something like [vim's recording mode](http://vim.wikia.com/wiki/Recording_keys_for_repeated_jobs) to get the desired effect; have a command that toggles a recording on/off and another command that plays it back. While there is an active recording, clone every `EditNotification` into the recording buffer before it gets dispatched to `do_edit`, `do_special`, et cetera.

I'm still super new to `xi`, so take all that with a grain of salt.

**Comment by cmyr** [comment]
Yea, so... there are a bunch of moving parts here, and you're welcome to investigate.

Currently, xi handles one command at a time. It makes sense to me that, at least for _edit_ commands, a client should be able to pass a sequence of them and get them applied together.

This has a number of implications:

currently, we render out changes after each command. This would need to change, in the 'batch command' mode; we would want to just aggregate all the updates and send them out at once.

currently, we update undo state on a per-command basis; same situation as above; we would want a 'batch' command to create at most a single new undo group.

Realistically, this will involve a bunch of exploration. You should look at how we handle RPCs currently (they're all listed in `core-lib/src/rpc.rs`, and RPCs arrive at `core-lib/src/core.rs`; you can explore from there how they move through the rest of the system.) I think your first step would be adding a new `batch_edit` RPC, that accepts a list of commands.

There's some other weirdness here as well, such as that our RPC system treats notifications (which do not get responded to directly) differently from requests (which do), at a type level. So it would be currently tricky to batch together notifications _and_ requests. This shouldn't be the end of the world, though, since there aren't very many edit notifications (cut/copy only atm)

In any case, this is pretty open ended; you'll want to play around a bit and get a sense for how things work now, and then you can come up with your own idea of what might make sense?

**Comment by crazycoder997** [comment]
We do have the ability to transpose selection regions. One way we could think of transposing words is as a composition of the operations, 'select words' and 'transpose'.

That is: do we want to start thinking about every capability as an individual command, or do we want to create a vocabulary of command actions from which various capabilities can be composed?

To really reach the flexibility of an editor such as emacs/vim we'll probably want something like the latter. We've spoken about this previously (the idea of sending a series of commands as a single atomic command) but it's never really felt like a pressing issue.

**Comment by aeosynth** [comment]
just chiming in to say that while emacs has commands to transpose two regions, kakoune has commands to rotate any number of regions; a transpose can be seen as a two region rotation. does the xi transpose command already - or can it be extended to - work on multiple regions?

see [ROTATING](https://github.com/mawww/kakoune/blob/master/contrib/TRAMPOLINE) in the kakoune intro

**Comment by cmyr** [comment]
Our transpose as currently written will rotate any number of selected regions.
