### ISSUE TITLE
Undo history groups changes at inappropriate times

### ISSUE THREAD

**Issue by portstrom** [xi-editor/xi-editor#843]
When inserting or deleting multiple characters one after the other, the changes are grouped into a single entry in the undo history, so they can all be undone at once. That's normally a good thing, but when doing something else between the insertions, such as saving the file, or editing another file, the changes made after the interruption shouldn't be grouped with changes made before. Currently you can insert some character, save the file, insert some more characters, undo, and you will never get back to the state that matches the saved file.

**Comment by cmyr** [comment]
Yes saving currently does not influence undo behaviour. I think it's reasonable that it would. I think there are a number of other possible improvements here; for instance, it might make sense to create a new undo group on a timeout, so that only related edits that happen within some time window are treated as a single undo group.

In any case, maybe it would make more sense to rename this issue, "Save should create new undo group"? That will be a good isolated task for someone.
