### ISSUE TITLE
set up windows builds on Cirrus CI

### ISSUE THREAD

**Issue by cmyr** [xi-editor/xi-editor#844]
This should be relatively painless? https://cirrus-ci.org/guide/windows/

**Comment by LiHRaM** [comment]
I'll take this one.

**Comment by jansol** [comment]
@LiHRaM what's the status of this?

**Comment by LiHRaM** [comment]
@jansol I'd sort of considered this a done deal when you added support for Windows on Travis, as it is the ideal solution right now. (Turns out the MSVC tools are subject to license in docker containers, see [here](https://blogs.msdn.microsoft.com/vcblog/2018/08/13/using-msvc-in-a-docker-container-for-your-c-projects/).)

Anyway, the official rust team is still working out some kinks with supporting rust in docker images, and until they're done I think sticking with your solution is our best bet.

**Comment by jansol** [comment]
Let's close this then. We can open a new issue once we know we can do better.
