### ISSUE TITLE
core should send client a list of available languages on startup

### ISSUE THREAD

**Issue by cmyr** [xi-editor/xi-editor#863]
This will be the first step in letting clients manually specify or override the language for a file.

This involves adding a new core->client RPC, which will need to go in the documentation.

Implementation will be very similar to `available_themes`; indeed the language list is available in the `finish_init` fn in `tabs.rs`. 

This should be sent as a list of 'LanguageId' `String`s.

**Comment by daubaris** [comment]
Would love to work on this :) any tips?

**Comment by cmyr** [comment]
not much more than are in the original issue; take a look at how the `available_themes` RPC works, and maybe use that as a model? If you have any specific questions, you can ask them here or at irc.mozilla.org #xi. 😎

**Comment by daubaris** [comment]
Hi again, I've made some progress with this issue, but I've found myself cornered with language_list. 

As you've mentioned implementation should be very similar to `available_themes` fn.
So basically it should look like this:

```
pub fn available_languages(&self, languages: Vec<String>) {
    self.0.send_rpc_notification("available_languages",
                                 &json!({"languages": languages}))
}
```

Or should I pass a `Vec<LanguageId>`?

Also while looking into tabs.rs `finish_init` function I cant seem to find mentioned language list, because it's executed in the `finalize_new_views` fn in tabs.rs with a config.

Could you explain a bit further about this language list?

**Comment by cmyr** [comment]
yea, so you can send `LanguageId`s, which are just strings. You may need to add `#[derive(Serialize)]` to `LanguageId`. 

The fn in `tabs.rs` is actually called `finish_setup`.
